apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    app: confluent-rest-proxy
spec:
  replicas: {{ .Params.NODE_COUNT }}
  selector:
    matchLabels:
      app: confluent-rest-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: confluent-rest-proxy
    spec:
      containers:
      - name: confluent-rest-proxy
        image: confluentinc/cp-kafka-rest:5.3.2
        command:
          - bash
          - -c
        args:
          - /bootstrap/bootstrap.sh;
        resources:
          requests:
            memory: {{ .Params.MEMORY }}
            cpu: {{ .Params.CPUS }}
          limits:
            memory: {{ .Params.MEM_LIMIT }}
            cpu: {{ .Params.CPUS_LIMIT }}
        ports:
        - containerPort: {{ .Params.REST_PROXY_PORT }}
          name: rp-port
        env:
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL 
          value: {{ .Params.SCHEMA_REGISTRY_URL }}
        - name: KAFKA_REST_HOST_NAME
          value: {{ .Params.HOST_NAME }}
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: {{ .Params.KAFKA_BOOTSTRAP_SERVERS }}
        volumeMounts:
        - name: bootstrap
          mountPath: /bootstrap
        {{ if .Params.CUSTOM_RP_PROPERTIES_CM_NAME }}
        - name: custom-configuration
          mountPath: /custom-configuration
        {{ end }}
        livenessProbe:
          initialDelaySeconds: {{ .Params.LIVENESS_INITIAL_DELAY_SECONDS }}
          periodSeconds: {{ .Params.LIVENESS_PERIOD_SECONDS }}
          timeoutSeconds: {{ .Params.LIVENESS_TIMEOUT_SECONDS }}
          httpGet:
            path: /
            port: {{ .Params.REST_PROXY_PORT }}
      volumes:
        - name: bootstrap
          configMap:
            name: {{ .Name }}-bootstrap
            defaultMode: 0755
        {{ if .Params.CUSTOM_RP_PROPERTIES_CM_NAME }}
        - name: custom-configuration
          configMap:
            name: {{ .Params.CUSTOM_RP_PROPERTIES_CM_NAME }}
        {{ end }}
