apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
  namespace: {{ .Params.namespace }}
  labels:
    app: cockroachdb
spec:
  serviceName: {{ .Params.serviceName }}
  replicas: 3
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cockroachdb
              topologyKey: kubernetes.io/hostname
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach:{{ .Params.imageVersion }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: {{ .Params.requestCPU }}
            memory: {{ .Params.requestMemory }}
          limits:
              cpu: {{ .Params.limitCPU }}
              memory: {{ .Params.limitMemory }}
        ports:
        - containerPort: 26257
          name: grpc
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: '/health'
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: '/health?ready=1'
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        volumeMounts:
        - name: datadir
          mountPath: /cockroach/cockroach-data
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: COCKROACH_CHANNEL
          value: kubernetes-insecure
        command:
          - '/bin/bash'
          - '-ecx'
          - 'exec /cockroach/cockroach start --logtostderr --insecure --advertise-host $(echo $POD_NAME).cockroachdb --http-addr 0.0.0.0 --join cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb --cache 25% --max-sql-memory 25%'
      terminationGracePeriodSeconds: 60
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      {{ if ne .Params.storageClassName "default" }}
      storageClassName: {{ .Params.storageClassName }}
      {{ end }}
      accessModes:
        - 'ReadWriteOnce'
      resources:
        requests:
          storage: {{ .Params.storageSize }}

