apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .PlanName }}-job
  namespace: {{ .Namespace }}
spec:
  template:
    metadata:
      name: {{ .PlanName }}-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ .PlanName }}
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "mysql -u root -h {{ .Name }}-svc -p{{ .Params.PASSWORD }} -e \"CREATE TABLE example ( id smallint unsigned not null auto_increment, name varchar(20) not null, constraint pk_example primary key (id) );\" kudo "
