apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .PlanName }}-job
  namespace: {{ .Namespace }}
spec:
  template:
    metadata:
      name: {{ .PlanName }}-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ .PlanName }}
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "mysql -u root -h {{ .Name }}-svc -p{{ .Params.PASSWORD }} --database=kudo < /backups/{{ .Params.RESTORE_FILE }}"
        volumeMounts:
        - name: backup-pv
          mountPath: /backups
      volumes:
      - name: backup-pv
        persistentVolumeClaim:
          claimName: {{ .Name }}-backup-pv
