apiVersion: batch/v1
kind: Job
metadata:
  name: validation
spec:
  template:
    metadata:
      name: "validation"
    spec:
      restartPolicy: Never
      containers:
        - name: kubernetes-zookeeper
          imagePullPolicy: Always
          image: "zookeeper:3.4.14"
          env:
            - name: CONN
              value: zookeeper-0.hs:{{ .Params.CLIENT_PORT }},zookeeper-1.hs:{{ .Params.CLIENT_PORT }},zookeeper-2.hs:{{ .Params.CLIENT_PORT }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
          command:
            - bash
            - -c
            - "until bin/zkCli.sh -server $CONN ls /; do sleep 5; done"