apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-cruise-control-svc
  namespace: {{ .Namespace }}
  {{ if eq .Params.METRICS_ENABLED "true" }}
  labels:
    "kudo.dev/servicemonitor": "true"
  {{ end }}
spec:
  ports:
    - port: {{ .Params.CRUISE_CONTROL_PORT }}
      name: http
  clusterIP: None
  selector:
    app: cruise-control
    kudo.dev/instance: {{ .Name }}
