apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-connect-svc
  namespace: {{ .Namespace }}
  {{ if eq .Params.METRICS_ENABLED "true" }}
  labels:
    "kudo.dev/servicemonitor": "true"
  {{ end }}
spec:
  ports:
    - port: {{ .Params.KAFKA_CONNECT_REST_PORT }}
      name: server
  clusterIP: None
  selector:
    app: kafka-connect
    kudo.dev/instance: {{ .Name }}