apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Name }}-enable-tls
  namespace: {{ .Namespace }}
data:
  enable-tls.sh: |
    #!/usr/bin/env bash
    set -euxo pipefail
    
    mkdir -p /tmp/confluent-schema-registry/tls
    pushd /tmp/confluent-schema-registry/tls
    
    readonly certificate="tls.crt"
    readonly private_key="tls.key"
    
    # In days.
    readonly validity=900
    
    readonly server_keystore="confluent-schema-registry.server.keystore.jks"
    readonly server_truststore="confluent-schema-registry.server.truststore.jks"
    readonly client_truststore="confluent-schema-registry.client.truststore.jks"

    readonly storepass="changeit"
    readonly keypass="changeit"

    # COPY CA AUTHORITY CERTIFICATE AND KEY OBTAINED FROM SECRETS
    cp /etc/tls/certs/tls.crt /tmp/confluent-schema-registry/tls/tls.crt
    cp /etc/tls/certs/tls.key /tmp/confluent-schema-registry/tls/tls.key

    # GENERATE KEYSTORE AND TRUSTSTORE
    keytool -keystore "${server_keystore}" \
            -alias ${1} \
            -validity ${validity} \
            -genkey \
            -keyalg RSA \
            -dname "CN=${1}" \
            -storepass "${storepass}" \
            -keypass "${keypass}" \
            -noprompt
    # Add the CACert to the client and server truststores so that clients and server can trust this CA
    keytool -keystore "${client_truststore}" \
            -alias CARoot \
            -import \
            -file "${certificate}" \
            -storepass "${storepass}" \
            -noprompt
    keytool -keystore "${server_truststore}" \
            -alias CARoot \
            -importcert \
            -file "${certificate}" \
            -storepass "${storepass}" \
            -noprompt
    # Create a certificate signing request
    keytool -keystore "${server_keystore}" \
            -alias ${1} \
            -certreq \
            -file cert-req \
            -storepass "${storepass}"
    # Add openssl certificate signing extension config file
    cat > csr.conf <<EOF
    [ req_ext ]
    subjectAltName = @alt_names
    extendedKeyUsage = serverAuth, clientAuth

    [ alt_names ]
    DNS.1 = localhost
    DNS.2 = 127.0.0.1
    DNS.3 = $(hostname -f)
    DNS.4 = $(hostname -i)
    DNS.5 = $(hostname)
    IP.1 = 0.0.0.0
    IP.2 = 127.0.0.1
    IP.3 = $(hostname -i)
    EOF
    # Sign the certificate with the CA & CAKey
    openssl x509 -req \
        -CA /tmp/confluent-schema-registry/tls/${certificate} \
        -CAkey /tmp/confluent-schema-registry/tls/${private_key} \
        -in cert-req \
        -out cert-signed \
        -days ${validity} \
        -CAcreateserial \
        -passin pass:"${storepass}" \
        -extfile csr.conf \
        -extensions req_ext
    # Import the CA cert into server keystore
    keytool -keystore "${server_keystore}" \
            -alias CARoot \
            -import \
            -file "/tmp/confluent-schema-registry/tls/${certificate}" \
            -storepass "${storepass}" -noprompt
    # Import the signed certificate into server keystore
    keytool -keystore "${server_keystore}" \
            -alias ${1} \
            -import \
            -file cert-signed \
            -storepass "${storepass}" -noprompt
    popd
