apiVersion: apps/v1
kind: Deployment
metadata:
  name: actor
spec:
  replicas: 1
  selector:
    matchLabels:
      actor: {{ .Name }}
  template:
    metadata:
      name: flink-demo-actor
      labels:
        actor: {{ .Name }}
    spec:
      containers:
        - name: actor
          image: dcoslabs/flink-demo-actor:0.3
          command: ["/fraudDisplay-linux"]
          imagePullPolicy: Always
          args: ["--broker", "kafka-kafka-0.kafka-svc:9093"]
