{{ range $i, $v := until (int .Params.NODE_COUNT) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: backup-node-{{ $v }}
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: {{ $.Name }}-sa
      containers:
        - name: backup
          image: bitnami/kubectl:{{ $.Params.KUBECTL_VERSION }}
          command:
            - bash
            - -c
          args:
            - kubectl -n {{ $.Namespace }} exec {{ $.Name }}-node-{{ $v }} --container medusa-backup -- python3 /usr/local/bin/medusa backup --backup-name {{ $.Params.BACKUP_NAME }}
      restartPolicy: Never
{{ end }}