apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Name }}-binding
  namespace: {{ .Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Name }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Name }}-sa
    namespace: {{ .Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Name }}-sa
  namespace: {{ .Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Namespace }}
  name: {{ .Name }}-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["update", "get", "list"]
