apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Name }}-generate-cqlshrc-sh
  namespace: {{ .Namespace }}
data:
  generate-cqlshrc.sh: |
    cat <<EOT >> ~/.cassandra/cqlshrc
    [connection]
    factory = cqlshlib.ssl.ssl_transport_factory
    hostname = ${POD_NAME}.{{ .Name }}-svc.{{ .Namespace }}.svc.cluster.local
    port = {{ .Params.NATIVE_TRANSPORT_PORT }}
    {{ if eq .Params.TRANSPORT_ENCRYPTION_CLIENT_ENABLED "true" }}
    ssl = true
    {{ end }}

    {{ if eq .Params.TRANSPORT_ENCRYPTION_CLIENT_ENABLED "true" }}
    [ssl]
    certfile = /etc/tls/certs/tls.crt
    {{ if eq .Params.TRANSPORT_ENCRYPTION_CLIENT_REQUIRE_CLIENT_AUTH "true" }}
    userkey = /etc/tls/certs/tls.key
    usercert = /etc/tls/certs/tls.crt
    {{ end }}
    {{ end }}

    {{ if .Params.AUTHENTICATION_SECRET_NAME }}
    [authentication]
    username = $(cat /etc/cassandra/authentication/username)
    password = $(cat /etc/cassandra/authentication/password)
    {{ end }}
    EOT
