{{ $topology := list 1 }}
{{ $nodeCount := $.Params.NODE_COUNT}}
{{ if $.Params.NODE_TOPOLOGY }}
{{ $topology = $.Params.NODE_TOPOLOGY }}
{{ end }}
{{ range $datacenter := $topology }}
{{ if $.Params.NODE_TOPOLOGY }}
  {{ $nodeCount := $datacenter.nodes }}
{{ end }}
{{ $minAvailable := sub $nodeCount 1}}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  {{ if $.Params.NODE_TOPOLOGY }}
  name: {{ $.Name }}-{{ $datacenter.datacenter }}-pdb
  {{ else }}
  name: {{ $.Name }}-pdb
  {{ end }}
  namespace: {{ $.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $.Name }}
      cassandra: {{ $.OperatorName }}
      {{ if $.Params.NODE_TOPOLOGY }}
      cassandra-dc: {{ $.OperatorName }}-{{ $datacenter.datacenter }}
      {{ end }}
      kudo.dev/instance: {{ $.Name }}
  minAvailable: {{ $minAvailable }}
{{ end }}