apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Name }}-monitor
  namespace: {{ .Namespace }}
  labels:
    app: prometheus-operator
    release: prometheus-kubeaddons
spec:
  endpoints:
    - interval: 30s
      port: prometheus-exporter-port
  namespaceSelector:
    matchNames:
      - {{ .Namespace }}
  selector:
    matchLabels:
      kudo.dev/instance: {{ .Name }}
      kudo.dev/servicemonitor: "true"
