apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-svc
  namespace: {{ .Namespace }}
  {{ if eq .Params.PROMETHEUS_EXPORTER_ENABLED "true" }}
  labels:
    kudo.dev/servicemonitor: "true"
  {{ end }}
spec:
  ports:
    - port: {{ .Params.STORAGE_PORT }}
      name: storage
    - port: {{ .Params.SSL_STORAGE_PORT }}
      name: ssl-storage
    - port: {{ .Params.NATIVE_TRANSPORT_PORT }}
      name: native-transport
    {{ if eq .Params.START_RPC "true" }}
    - port: {{ .Params.RPC_PORT }}
      name: rpc
    {{ end }}
    {{ if ne .Params.JMX_LOCAL_ONLY "true" }}
    - port: {{ .Params.JMX_PORT }}
      name: jmx
    - port: {{ .Params.RMI_PORT }}
      name: rmi
    {{ end }}
    {{ if eq .Params.PROMETHEUS_EXPORTER_ENABLED "true" }}
    - port: {{ .Params.PROMETHEUS_EXPORTER_PORT }}
      name: prometheus-exporter-port
    {{ end }}
  selector:
    app: {{ .Name }}
    kudo.dev/instance: {{ .Name }}
