# framework instance

apiVersion: kudo.k8s.io/v1alpha1
kind: Instance
metadata:
  name: myes
  labels:
    controller-tools.k8s.io: "1.0"
    framework: elastic
spec:
  frameworkVersion:
    name: elastic-v1
    namespace: default
    type: FrameworkVersions
