apiVersion: kudo.dev/v1beta1
parameters:
  - name: HOST_NAME
    description: "Host name used to generate absolute URLs in responses"
    default: "confluent-rest-proxy"
  - name: NODE_COUNT
    description: "Number of nodes that would be running Confluent REST Proxy service"
    default: "1"
  - name: SCHEMA_REGISTRY_URL
    description: "The base URL for Confluent Schema Registry that should be used by the Avro serializer"
    default: "http://confluent-schema-registry:8081/"
  - name: KAFKA_BOOTSTRAP_SERVERS
    description: "A list of Kafka brokers to connect to. Eg. PLAINTEXT://hostname:9092"
    default: "PLAINTEXT://kafka-instance-kafka-0.kafka-instance-svc:9093,PLAINTEXT://kafka-instance-kafka-1.kafka-instance-svc:9093,PLAINTEXT://kafka-instance-kafka-2.kafka-instance-svc:9093"
  - name: REST_PROXY_PORT
    description: "Port on which Confluent REST Proxy will be exported to listen on for new connections"
    default: 8082
  - name: REST_PROXY_PORT_TLS
    description: "Port on which Confluent REST Proxy will be exported to listen on for new connections when transport encryption is enabled"
    default: 8083
  - name: MEMORY
    description: "Amount of memory to provide to Confluent REST Proxy pods"
    default: "256Mi"
  - name: MEM_LIMIT
    description: "Memory (limit) for the Confluent REST Proxy nodes pods. spec.containers[].resources.limits.memory"
    default: "1024Mi"
  - name: CPUS
    description: Amount of cpu to provide to Confluent REST Proxy pods
    default: "250m"
  - name: CPUS_LIMIT
    description: "CPUs (limit) for the Confluent REST Proxy nodes pods. spec.containers[].resources.limits.cpu"
    default: "1000m"
  - name: LIVENESS_INITIAL_DELAY_SECONDS
    displayName: "livenessProbe initial delay timeout seconds"
    description: "Number of seconds after the container has started before liveness probes is initiated."
    default: "30"
  - name: LIVENESS_PERIOD_SECONDS
    displayName: "livenessProbe period seconds"
    description: "How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1."
    default: "10"
  - name: LIVENESS_TIMEOUT_SECONDS
    displayName: "livenessProbe timeout seconds"
    description: "Number of seconds after which the probe times out. Defaults to 10 seconds. Minimum value is 1."
    default: "10"
  - name: CUSTOM_RP_PROPERTIES_CM_NAME
    displayName: "custom server properties configmap name"
    description: "The properties present in this configmap will be appended to the Rest Proxy properties"
    required: false
  - name: TRANSPORT_ENCRYPTION_ENABLED
    displayName: "Enable transport encryption (TLS)"
    description: "Enable transport encryption (TLS)"
    default: "false"
  - name: TLS_SECRET_NAME
    default: "confluent-rest-proxy-tls"
    displayName: "confluent-rest-proxy-tls"
    description: "The secret that contains TLS certificate and is mounted as a volume to make them available to rest proxy."
  - name: TRANSPORT_ENCRYPTION_CIPHERS
    displayName: "Cipher Suite Names"
    description: "Comma-separated list of JSSE Cipher Suite Names"
    default: "TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
  - name: TRANSPORT_ENCRYPTION_CLIENT_ALLOW_PLAINTEXT
    displayName: "Allow Plaintext Traffic with rest-proxy clients"
    description: "Allow plaintext alongside encrypted traffic with rest-proxy clients"
    default: "false"
  - name: SSL_AUTHENTICATION_KAFKA_CLIENT_NAME
    displayName: "SSL Authentication Client Name"
    description: "The name used as the client certificate CN(Common Name) when communicating with Kafka over TLS"
    default: "RestProxyClient"
  - name: TRANSPORT_ENCRYPTION_CLIENT_ENABLED
    displayName: "Enable transport encryption (TLS) with rest proxy clients"
    description: "Enable transport encryption (TLS) with rest proxy clients"
    default: "false"
  - name: SSL_AUTHENTICATION_CLIENT_ENABLED
    displayName: "Enable SSL authentication for Rest-Proxy clients"
    description: "Enable SSL authentication for Rest-Proxy clients"
    default: "false"
  - name: TLS_CLIENT_SECRET_NAME
    default: "confluent-rest-proxy-client-tls"
    displayName: "confluent-rest-proxy-client-tls"
    description: "The secret that contains TLS certificate and is mounted as a volume to make them available to rest proxy."
  - name: TRANSPORT_ENCRYPTION_CLIENT_CIPHERS
    displayName: "Cipher Suite Names"
    description: "Comma-separated list of JSSE Cipher Suite Names"
    default: "TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
