apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Namespace }}
  name: {{ .Name }}-{{ .OperatorName }}-pdb
  labels:
    app: redis
    redis: {{ .OperatorName }}
    instance: {{ .Name }}
spec:
  selector:
    matchLabels:
      app: redis
      redis: {{ .OperatorName }}
      instance: {{ .Name }}
  minAvailable: 2
