parameters:
  - name: BACKUP_FILE
    description: "Filename to save the backups to"
    default: "backup.sql"
    displayName: "BackupFile"
    trigger: backup
  - name: PASSWORD
    default: "password"
