{
 "title": "Spark Operator",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Spark_Operator_Instance",
    "label": "Spark Operator Instance",
    "query": "label_values(kube_pod_labels{label_app_kubernetes_io_name=\"spark\"}, pod)"
   },
   {
    "name": "Spark_Metrics_Endpoint",
    "label": "Spark Metrics Endpoint",
    "query": "label_values(spark_app_submit_count, endpoint)"
   }
  ]
 },
 "panels": [
  { "title": "SparkApplication and Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Submitted SparkApplications",
   "type": "singlestat",
   "description": "Total number of SparkApplication submitted by the Operator.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_submit_count{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed SparkApplications",
   "type": "singlestat",
   "description": "Total number of SparkApplication which failed to complete.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_failure_count{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}"
    }
   ]
  },
  {
   "title": "Execution time for SparkApplications which succeeded.",
   "type": "graph",
   "description": "Execution time for applications which succeeded.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "spark_app_success_execution_time_microseconds{pod=\"$Spark_Operator_Instance\"}",
     "legendFormat": "quantile-{{quantile}}"
    }
   ]
  },
  {
   "title": "Execution time for SparkApplications which failed.",
   "type": "graph",
   "description": "Execution time for applications which failed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "spark_app_failure_execution_time_microseconds{pod=\"$Spark_Operator_Instance\"}",
     "legendFormat": "quantile-{{quantile}}"
    }
   ]
  },
  {
   "title": "Running SparkApplications",
   "type": "singlestat",
   "description": "Total number of SparkApplication which are currently running.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_running_count{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Spark Executors",
   "type": "singlestat",
   "description": "Total number of Spark Executors which failed.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_executor_failure_count{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Succ. completed SparkApplications.",
   "type": "singlestat",
   "description": "Total number of SparkApplication which completed successfully.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_success_count{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Running Spark Executors",
   "type": "singlestat",
   "description": "Total number of Spark Executors which are currently running.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_executor_running_count{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}"
    }
   ]
  },
  {
   "title": "Succ. Completed Spark Executors",
   "type": "singlestat",
   "description": "Total number of Spark Executors which completed successfully.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_executor_success_count{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}"
    }
   ]
  },
  { "title": "SparkApplication Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Adds handled by work queue",
   "type": "singlestat",
   "description": "Total number of adds handled by work queue",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_application_controller_adds{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current depth of work queue",
   "type": "gauge",
   "description": "Current depth of work queue",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "spark_application_controller_depth{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}"
    }
   ]
  },
  {
   "title": "Latency for work queue",
   "type": "graph",
   "description": "Latency for work queue",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "spark_application_controller_latency{pod=\"$Spark_Operator_Instance\"}",
     "legendFormat": "quantile-{{quantile}}"
    }
   ]
  },
  {
   "title": "Processing an item from work queue duration",
   "type": "graph",
   "description": "How long processing an item from workqueue takes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "spark_application_controller_work_duration{pod=\"$Spark_Operator_Instance\"}",
     "legendFormat": "quantile-{{quantile}}"
    }
   ]
  },
  {
   "title": "Retries handled by work queue",
   "type": "singlestat",
   "description": "Total number of retries handled by work queue",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_application_controller_retries{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}"
    }
   ]
  },
  {
   "title": "Unfinished work",
   "type": "singlestat",
   "description": "Unfinished work in seconds",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_application_controller_unfinished_work_seconds{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}"
    }
   ]
  },
  {
   "title": "Longest running processor",
   "type": "singlestat",
   "description": "Longest running processor in microseconds",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_application_controller_longest_running_processor_microseconds{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}"
    }
   ]
  },
  {
   "title": "ScheduledApplication Work Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Adds handled by work queue",
   "type": "singlestat",
   "description": "Total number of adds handled by workqueue",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scheduled_spark_application_controller_adds{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current depth of work queue",
   "type": "gauge",
   "description": "Current depth of work queue",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
   "targets": [
    {
     "expr": "scheduled_spark_application_controller_depth{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}"
    }
   ]
  },
  {
   "title": "Latency for work queue",
   "type": "graph",
   "description": "Latency for work queue",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "scheduled_spark_application_controller_latency{pod=\"$Spark_Operator_Instance\"}",
     "legendFormat": "quantile-{{quantile}}"
    }
   ]
  },
  {
   "title": "Processing an item from work queue duration",
   "type": "graph",
   "description": "How long processing an item from workqueue takes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "scheduled_spark_application_controller_work_duration{pod=\"$Spark_Operator_Instance\"}",
     "legendFormat": "quantile-{{quantile}}"
    }
   ]
  },
  {
   "title": "Retries handled by work queue",
   "type": "singlestat",
   "description": "Total number of retries handled by work queue",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scheduled_spark_application_controller_retries{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}"
    }
   ]
  },
  {
   "title": "Unfinished work",
   "type": "singlestat",
   "description": "Unfinished work in seconds",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scheduled_spark_application_controller_unfinished_work_seconds{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}"
    }
   ]
  },
  {
   "title": "Longest running processor",
   "type": "singlestat",
   "description": "Longest running processor in microseconds",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scheduled_spark_application_controller_longest_running_processor_microseconds{pod=\"$Spark_Operator_Instance\", endpoint=\"$Spark_Metrics_Endpoint\"}"
    }
   ]
  }
 ]
}