kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq-peer-discovery-rbac
  namespace: {{ .Namespace }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]