apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-svc
  namespace: {{ .Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Params.AMQP_PORT }}
    name: amqp
  - port: {{ .Params.MANAGEMENT_PORT }}
    name: management
  selector:
    app: rabbitmq
    kudo.dev/instance: {{ .Name }}